// build-api.mjs: replace the committed function entry with one self-contained JS bundle.
//
// Why: Vercel plans the functions of a deployment from the source tree *before* the build command
// runs, so the entry has to exist in git (`app/api/index.js`, a thin re-export for planning). The
// platform then compiles `server/src/*.ts` with its own `tsc` run, keeps the `.ts` import
// specifiers in the emitted JS, and ships only the `.js` files — the function would die on its
// first import. Bundling here, after planning and before the platform collects the function
// package, replaces the entry with one file that needs no further resolution
// (docs/DECISIONS.md D-24).
//
// Third-party packages are bundled too: only the native libSQL driver stays external, and it is
// reached exclusively for `file:` targets, which production never uses (Turso over HTTP). The
// database schema travels inside the bundle as the `db/schema.ts` module, so no asset has to be
// traced.
import { readFileSync } from 'node:fs';
import { stat, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const entry = join(root, 'api', 'index.js');

const nativeDriver = {
  name: 'native-libsql-external',
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /^(@libsql\/client|libsql)$/ }, (args) => ({ path: args.path, external: true }));
  },
};

await build({
  entryPoints: [join(root, 'server', 'src', 'vercel.ts')],
  outfile: entry,
  bundle: true,
  platform: 'node',
  target: 'node24',
  format: 'esm',
  sourcemap: false,
  logLevel: 'warning',
  plugins: [nativeDriver],
  // Bundled CJS dependencies (Fastify, pino) call `require('node:events')` and friends. ESM output
  // has no `require`, and esbuild's fallback throws "Dynamic require of … is not supported", so the
  // bundle carries a real one.
  banner: {
    js: "import { createRequire as __createRequire } from 'node:module'; const require = __createRequire(import.meta.url);",
  },
});

const banner = `// Generated by scripts/build-api.mjs from server/src/vercel.ts — do not edit by hand.\n`;
const source = readFileSync(entry, 'utf8');
await writeFile(entry, banner + source);

console.log(`api/index.js ${Math.round((await stat(entry)).size / 1024)} KB (bundel fungsi Vercel)`);
